name: Convert raw URLs

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'raw-domain.txt'
      - 'raw-subdomain.txt'

permissions:
  contents: write

jobs:

  convert:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.x"
    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 'lts/*'
    - name: Install fop-rs
      run: |
         npm install -g fop-cli
    - name: Convert URLs to Domain, then sort with fop.py
      run: |
        pip install tldextract
        cat raw-domain.txt | python3 scripts/url-to-domain.py | sort -u >> domains.txt
        cat raw-subdomain.txt | python3 scripts/url-to-domain-subdomain.py | sort -u >> domains.txt
        > raw-domain.txt
        > raw-subdomain.txt
        fop -n .
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Converted raw URLs, List updated."
        git push

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
