name: Filter Orderer and Preener

on:
  workflow_dispatch:

permissions:
  contents: write


jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run Scripts
      run: |
        python $GITHUB_WORKSPACE/scripts/fop.py
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Filter Orderer and Preener"
        git push
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
