name: PyFunceble

on:
  workflow_dispatch:
  schedule:
   - cron: "0 * * * *"

permissions:
  contents: write
  
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install PyFunceble
      run: |
        python -m pip install --upgrade pip
        pip install pyfunceble

    - name: Check dead domains, upload the commands output
      run: |
        rm pyfunceable-output.txt
        pyfunceble -f /home/runner/work/anti-gambling-domains/anti-gambling-domains/domains.txt >> pyfunceable-output.txt

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "ABPindo Update"
        git push
      continue-on-error: true
        
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
